import type { RoundMemo, StageDefinition } from './types';

export const TRAUMA_STAGES: StageDefinition[] = [
  {
    id: 'initial',
    index: 'Ⅰ级',
    name: '战现场急救',
    note: '首次、简易、快速处置',
    substeps: [
      { name: '初级急救', note: '连抢救组' },
      { name: '高级急救', note: '营救护站' },
    ],
  },
  {
    id: 'early',
    index: 'Ⅱ级',
    name: '早期救治',
    note: '控制伤情发展',
    substeps: [
      { name: '紧急处置', note: '旅（团）救护所' },
      { name: '外科复苏', note: '增强手术力量' },
    ],
  },
  {
    id: 'specialist',
    index: 'Ⅲ级',
    name: '专科治疗',
    note: '消除损伤危害',
    substeps: [
      { name: '野战专科救治', note: '野战医疗所' },
      { name: '确定性专科治疗', note: '后方医院' },
    ],
  },
  {
    id: 'rehab',
    index: 'Ⅳ级',
    name: '康复治疗',
    note: '促进身心功能恢复',
    substeps: [
      { name: '功能恢复', note: '功能评估与训练' },
      { name: '身心康复', note: '心理与适应支持' },
    ],
  },
];

const sharedEvidence = {
  source: '远程知识库' as const,
  used: true,
};

export const DEMO_TRAUMA_ROUNDS: RoundMemo[] = [
  {
    id: 'round-1',
    round: 1,
    title: '首次报告',
    time: '15:01',
    elapsed: '06 min',
    stageId: 'initial',
    substepIndex: 0,
    facility: '连抢救组',
    capability: '初级急救',
    transitionLabel: '等待补充信息',
    nextTarget: '待判断',
    inputPoints: ['爆炸后胸痛、呼吸急促', '右小腿开放伤伴活动性出血', '意识清楚，可正常对答'],
    actionPoints: ['按气道—呼吸—循环顺序检伤', '直接压迫小腿伤口并包扎固定', '补充关键生命体征'],
    conclusion: '先排查危及生命问题，补齐生命体征后重新分类。',
    patient: {
      updatedAt: '15:01 · 伤后 06 min',
      consciousness: '清醒，能正常对答（GCS 15）',
      vitals: [
        { label: '呼吸', value: '未测', trend: 'unknown' },
        { label: '收缩压', value: '未测', trend: 'unknown' },
        { label: '心率', value: '未测', trend: 'unknown' },
        { label: '血氧', value: '未测', trend: 'unknown' },
      ],
      injuries: [
        { label: '胸部损伤（胸痛、呼吸急促）', certainty: '疑似', status: '活动' },
        { label: '右小腿开放性创伤伴出血', certainty: '已确认', status: '活动性出血' },
      ],
      treatments: ['初步检伤评估（进行中）', '右小腿伤口直接压迫止血（进行中）'],
      missingInformation: ['呼吸频率', '收缩压', '心率', '血氧饱和度', '胸部是否开放伤'],
    },
    classification: {
      label: '急救分类 · v1',
      severity: '待进一步评估',
      treatmentPriority: '待分类',
      transportPriority: '尚未判断',
    },
    timing: { window: '初级急救宜在伤后 10 分钟内实施', status: '处于建议时限内' },
    gate: {
      status: 'ASSESSING',
      title: '暂不触发阶段转换',
      description: '当前信息不足，先完成伤情评估与本级处置。',
      confirmation: 'Gate 未达 READY，本轮不发起阶段转换确认。',
    },
    actions: ['确认呼吸、循环和活动性出血', '完成止血、包扎固定和安全搬运准备', '补充关键生命体征后重新分类'],
    nextStageCapability: '胸部伤进一步评估需高级急救及以上能力。',
    messages: [
      {
        role: 'user',
        text: '爆炸后有一名伤员，胸口受伤，现在呼吸很急、胸部疼痛，右小腿还有伤口在流血，人目前能正常回答问题。',
      },
      {
        role: 'assistant',
        text: '已结合检索到的《战伤救治规则》战现场急救、胸部伤现场处置和急救分类知识块进行研判。\n\n**初步研判**：当前位于Ⅰ级战现场急救—初级急救。伤员意识尚清楚，但存在呼吸急促、胸痛和右小腿活动性出血，应先按气道、呼吸、循环顺序排查危及生命的问题；现阶段只能确认「胸部伤与四肢开放伤风险」，暂不能仅凭描述判定具体胸部伤类型。\n\n**当前救治方案**：立即检查口腔及气道是否通畅，持续观察呼吸费力、胸廓起伏是否对称；对右小腿伤口实施直接压迫并评估止血效果，随后完成包扎、固定和安全搬运准备。检查胸壁是否存在开放伤口、反常呼吸或明显变形。同步记录负伤时间、处置时间和意识变化。\n\n**需要补充**：请尽快提供呼吸频率、收缩压、心率、血氧饱和度（如有）、胸部是否开放伤，以及压迫后小腿出血能否控制。\n\n仅供辅助，须具备资质的医务人员复核。',
      },
    ],
    evidence: [
      {
        id: 'r1-e1',
        title: '第二十四条【战现场急救—初级急救】',
        score: '相关度 0.96',
        text: '初级急救包括检伤评估、止血、通气、包扎、固定与搬运等措施。',
        ...sharedEvidence,
      },
      {
        id: 'r1-e2',
        title: '第一〇五条【胸部伤战现场急救】',
        score: '相关度 0.92',
        text: '胸部伤战现场急救应保持呼吸道通畅，按伤情实施包扎固定，并在有条件时吸氧。',
        ...sharedEvidence,
      },
    ],
  },
  {
    id: 'round-2',
    round: 2,
    title: '生命体征补充',
    time: '15:09',
    elapsed: '14 min',
    stageId: 'initial',
    substepIndex: 0,
    facility: '连抢救组',
    capability: '初级急救 → 能力不足',
    transitionLabel: '已确认转入高级急救',
    transitionTone: 'warning',
    nextTarget: '营救护站 · 高级急救',
    inputPoints: ['RR 32、SBP 95、HR 120', '右胸随呼吸剧痛，无明显开放伤', '小腿压迫后基本止血'],
    actionPoints: ['维持止血效果并完成后送固定', '持续监测呼吸、血压、心率与意识', '携伤情与处置信息准备转运'],
    conclusion: '主要风险转向胸部与循环，经用户确认后转入高级急救。',
    patient: {
      updatedAt: '15:09 · 伤后 14 min',
      consciousness: '清醒，能对答，主诉右胸剧痛',
      vitals: [
        { label: '呼吸', value: '32 次/分', trend: 'up', abnormal: true },
        { label: '收缩压', value: '95 mmHg', trend: 'down', abnormal: true },
        { label: '心率', value: '120 次/分', trend: 'up', abnormal: true },
        { label: '血氧', value: '未测', trend: 'unknown' },
      ],
      injuries: [
        { label: '胸部闭合性损伤（待排气胸/血胸）', certainty: '疑似', status: '持续' },
        { label: '右小腿开放性创伤', certainty: '已确认', status: '出血已控制' },
        { label: '胸壁开放性伤口', certainty: '已排除', status: '本轮未见' },
      ],
      treatments: ['右小腿直接压迫止血（已完成）', '加压包扎与肢体固定（已完成）', '生命体征监测（进行中）'],
      missingInformation: ['血氧饱和度', '双侧呼吸音', '末梢循环', '血压趋势'],
    },
    classification: {
      label: '急救分类 · v2',
      severity: '重伤风险 · 需复评',
      treatmentPriority: '高优先级',
      transportPriority: '优先后送',
    },
    timing: { window: '初级急救宜在伤后 10 分钟内实施', status: '超过建议时限 4 分钟', warning: true },
    gate: {
      status: 'READY',
      title: '满足后送条件，已由用户确认',
      description: '小腿出血已控制，胸部伤评估需要更高救治能力。',
      confirmation: '15:10 已确认转入Ⅰ级·高级急救（营救护站）。',
    },
    actions: ['持续监测呼吸、血压、心率与意识', '维持止血效果并完成后送固定', '优先转入高级急救单元'],
    nextStageCapability: '胸腔穿刺减压、容量复苏等属高级急救及以上能力。',
    messages: [
      {
        role: 'user',
        text: '呼吸大约每分钟32次，胸口没有明显开放伤，但右侧胸部呼吸时疼得厉害。收缩压95，心率120。小腿压迫后基本止住血了。',
      },
      {
        role: 'assistant',
        text: '已结合急救分类、胸部伤战现场急救和救送结合知识块重新研判。\n\n**伤情变化**：呼吸32次/分、收缩压95mmHg、心率120次/分提示呼吸与循环状态异常；右小腿压迫后基本止血，主要风险已转向胸部损伤及循环不稳定。救治优先级上调为高优先级，仍需排查张力性气胸、血胸、肺挫伤或持续失血。\n\n**当前救治方案**：继续保持气道通畅并持续监测生命体征；有条件时由专业人员给予吸氧。复查小腿包扎是否继续有效并完成肢体固定，避免搬运再次出血。胸部无明显开放伤，不直接执行开放性胸伤处置，但应持续观察呼吸困难是否加重、胸廓是否对称、意识是否改变。\n\n**阶段建议**：连抢救组的初级急救能力不足以完成进一步胸部伤评估，建议优先后送至具备高级急救能力的营救护站。Gate = READY，是否执行转换需要您确认。\n\n仅供辅助，须具备资质的医务人员复核。',
        ask: {
          header: '阶段转换',
          question: '是否确认将救治阶段转入「Ⅰ级 · 高级急救（营救护站）」？',
          options: [
            { label: '确认转入高级急救', description: '胸部伤评估需更高能力；后送优先级=优先，转运条件已满足' },
            { label: '暂不转换，继续本级处置', description: '维持初级急救，等待生命体征进一步变化' },
          ],
          answer: '确认转入高级急救',
        },
      },
    ],
    evidence: [
      {
        id: 'r2-e1',
        title: '第十六条【急救分类】',
        score: '相关度 0.95',
        text: '急救分类应根据生命体征和伤情，确定救治与后送优先顺序。',
        ...sharedEvidence,
      },
      {
        id: 'r2-e2',
        title: '第二十一条【救送结合原则】',
        score: '相关度 0.91',
        text: '伤情稳定时应尽快组织后送；危及生命时应先稳定伤情。',
        ...sharedEvidence,
      },
    ],
  },
  {
    id: 'round-3',
    round: 3,
    title: '到达营救护站',
    time: '15:25',
    elapsed: '30 min',
    stageId: 'initial',
    substepIndex: 1,
    facility: '营救护站',
    capability: '高级急救',
    transitionLabel: '已进入高级急救',
    nextTarget: '视复评结果确定',
    inputPoints: ['已送达营救护站', '收缩压仍约 95，呼吸仍快', '首次测得 SpO₂ 92%'],
    actionPoints: ['重新检伤、评估与分类', '吸氧与持续生命体征监护', '排查危及生命的胸部伤'],
    conclusion: '到站后异常未明显改善，生成急救分类 v3 并继续本级处置。',
    patient: {
      updatedAt: '15:25 · 伤后 30 min',
      consciousness: '清醒，反应稍迟，持续诉右胸痛',
      vitals: [
        { label: '呼吸', value: '30 次/分', trend: 'flat', abnormal: true },
        { label: '收缩压', value: '96 mmHg', trend: 'flat', abnormal: true },
        { label: '心率', value: '118 次/分', trend: 'flat', abnormal: true },
        { label: '血氧', value: '92%', trend: 'unknown', abnormal: true },
      ],
      injuries: [
        { label: '胸部闭合性损伤（气胸/血胸未排）', certainty: '疑似', status: '未改善' },
        { label: '右小腿开放性创伤', certainty: '已确认', status: '出血控制中' },
      ],
      treatments: ['吸氧（进行中）', '连续生命体征监护（进行中）', '急救分类 v3（已完成）'],
      missingInformation: ['双侧呼吸音', '床旁超声或 X 线', '复苏后血压趋势'],
    },
    classification: {
      label: '急救分类 · v3',
      severity: '重伤风险 · 持续',
      treatmentPriority: '高优先级',
      transportPriority: '待重新评估',
    },
    timing: { window: '高级急救宜在伤后 1 小时内实施', status: '处于建议时限内' },
    gate: {
      status: 'ASSESSING',
      title: '当前阶段继续处置',
      description: '到达新救治单元后重新评估，不沿用上一阶段分类。',
      confirmation: '本轮 Gate 为 ASSESSING，未发起阶段转换确认。',
    },
    actions: ['重新检伤、评估与分类', '实施本级范围内的呼吸循环支持', '判断当前能力能否满足后续救治'],
    nextStageCapability: 'X线、B超、血气和胸腔闭式引流属Ⅱ级早期救治能力。',
    messages: [
      {
        role: 'user',
        text: '现在已经送到营救护站了，血压还是95左右，呼吸仍然很快。',
      },
      {
        role: 'assistant',
        text: '已结合高级急救技术范围、分级救治任务和胸部伤救治知识块完成到站复评。\n\n**阶段确认**：伤员已到达营救护站，当前处于Ⅰ级战现场急救—高级急救。系统不沿用上一地点的分类结论，已生成急救分类 v3。血压仍约95mmHg、呼吸持续增快、血氧92%，说明异常没有明显改善。\n\n**当前救治方案**：重新完成检伤、评估与分类，连续监测呼吸、血压、心率、意识与血氧；复核胸部体征并重点排查张力性气胸、血气胸等危及生命的胸部伤。按高级急救能力建立必要生命支持与复苏条件；任何穿刺、切开等侵入性处置必须在明确指征后由具备资质的专业人员实施。\n\n**阶段建议**：Gate = ASSESSING，暂不发起转换。若高级急救后呼吸循环仍不改善，或需要X线/B超、血气检查与抗休克治疗，则启动进入Ⅱ级早期救治的评估。\n\n仅供辅助，须具备资质的医务人员复核。',
      },
    ],
    evidence: [
      {
        id: 'r3-e1',
        title: '第二十四条【高级急救】',
        score: '相关度 0.97',
        text: '高级急救包括检伤评估、呼吸维持、止血控制与生命支持。',
        ...sharedEvidence,
      },
      {
        id: 'r3-e2',
        title: '第十一条【分级救治任务】',
        score: '相关度 0.94',
        text: '营救护站及相当级别机构主要执行高级急救技术范围。',
        ...sharedEvidence,
      },
    ],
  },
  {
    id: 'round-4',
    round: 4,
    title: '后送受阻',
    time: '15:39',
    elapsed: '44 min',
    stageId: 'initial',
    substepIndex: 1,
    facility: '营救护站',
    capability: '高级急救 → 需早期救治',
    transitionLabel: '后送 Gate 暂缓',
    transitionTone: 'danger',
    nextTarget: '旅（团）救护所 · 早期救治',
    inputPoints: ['本级处置后仍呼吸困难', 'SBP 92，SpO₂ 降至 90%', '心率升至 126 次/分'],
    actionPoints: ['维持气道与呼吸支持', '按指征实施容量复苏', '联络接收机构并准备后送资料'],
    conclusion: '已需Ⅱ级能力，但伤情未稳定，Gate 阻塞且不发起确认。',
    patient: {
      updatedAt: '15:39 · 伤后 44 min',
      consciousness: '清醒但烦躁，回答简短',
      vitals: [
        { label: '呼吸', value: '34 次/分', trend: 'up', abnormal: true },
        { label: '收缩压', value: '92 mmHg', trend: 'down', abnormal: true },
        { label: '心率', value: '126 次/分', trend: 'up', abnormal: true },
        { label: '血氧', value: '90%', trend: 'down', abnormal: true },
      ],
      injuries: [
        { label: '胸部闭合性损伤（疑气胸/血胸）', certainty: '疑似', status: '恶化' },
        { label: '失血性或梗阻性休克倾向', certainty: '疑似', status: '进展' },
        { label: '右小腿开放性创伤', certainty: '已确认', status: '出血已控制' },
      ],
      treatments: ['呼吸支持（进行中）', '容量复苏（进行中）', '后送资料准备（进行中）'],
      missingInformation: ['血气或床旁超声', '容量复苏后反应', '途中监护条件'],
    },
    classification: {
      label: '急救分类 · v4',
      severity: '重伤风险 · 未改善',
      treatmentPriority: '紧急关注',
      transportPriority: '紧急后送',
    },
    timing: { window: '高级急救宜在伤后 1 小时内实施', status: '接近建议时限', warning: true },
    gate: {
      status: 'BLOCKED',
      title: '需要后送，但暂不满足转运条件',
      description: '伤情未稳定，应先完成必要稳定处置，再评估后送。',
      confirmation: '后送优先级=紧急，转运条件=不满足；本轮不发起阶段转换确认。',
    },
    actions: ['继续必要稳定处置与连续监护', '同步联络早期救治机构', '以生命体征趋势作为再次评估输入'],
    nextStageCapability: '胸腔闭式引流、输血抗休克与辅助检查需Ⅱ级能力。',
    messages: [
      {
        role: 'user',
        text: '高级急救处置后，伤员呼吸还是快，血压偏低，人比刚才更烦躁一点。',
      },
      {
        role: 'assistant',
        text: '已结合救送结合原则、后送医学评估和早期救治任务知识块完成再评估。\n\n**伤情变化**：呼吸仍快、血压偏低、烦躁加重，提示循环状态未纠正、组织灌注不足，胸部损伤合并失血风险上升，救治优先级维持在紧急救治。\n\n**当前救治方案**：继续在本级能力范围内实施必要的稳定处置与连续监护，重点观察呼吸困难、胸廓对称性、意识和血压趋势；维持四肢止血与固定，避免搬运造成二次损伤。\n\n**阶段建议**：Gate = BLOCKED。伤情尚未稳定，直接后送风险较高，本轮不发起阶段转换确认。建议先稳定生命体征，同时同步联络旅（团）救护所，做好Ⅱ级早期救治（胸腔闭式引流、输血抗休克、辅助检查）的准备。\n\n仅供辅助，须具备资质的医务人员复核。',
      },
    ],
    evidence: [
      {
        id: 'r4-e1',
        title: '第二十一条【救送结合原则】',
        score: '相关度 0.98',
        text: '伤情稳定时应尽快后送；伤情恶化危及生命时应优先稳定伤情。',
        ...sharedEvidence,
      },
      {
        id: 'r4-e2',
        title: '第二十二条【救送结合实施】',
        score: '相关度 0.95',
        text: '后送前应组织医学评估，后送途中应实施连续医疗监护。',
        ...sharedEvidence,
      },
    ],
  },
  {
    id: 'round-5',
    round: 5,
    title: '进入Ⅱ级',
    time: '15:52',
    elapsed: '57 min',
    stageId: 'early',
    substepIndex: 0,
    facility: '旅（团）救护所',
    capability: '早期救治',
    transitionLabel: '阶段转换已完成',
    transitionTone: 'success',
    nextTarget: 'Ⅱ级 · 紧急处置',
    inputPoints: ['稳定处置后呼吸循环好转', '已具备转运条件并完成后送', '到达旅（团）救护所'],
    actionPoints: ['复查伤情并执行收容分类', '安排胸部影像、血气等辅助检查', '继续抗休克与胸部处置准备'],
    conclusion: '经用户确认后完成阶段转换，进入Ⅱ级紧急处置。',
    patient: {
      updatedAt: '15:52 · 伤后 57 min',
      consciousness: '清醒，对答顺畅，烦躁缓解',
      vitals: [
        { label: '呼吸', value: '26 次/分', trend: 'down', abnormal: true },
        { label: '收缩压', value: '104 mmHg', trend: 'up' },
        { label: '心率', value: '106 次/分', trend: 'down', abnormal: true },
        { label: '血氧', value: '95%', trend: 'up' },
      ],
      injuries: [
        { label: '胸部闭合性损伤（待辅助检查明确）', certainty: '疑似', status: '趋稳' },
        { label: '休克倾向', certainty: '疑似', status: '初步纠正' },
        { label: '右小腿开放性创伤', certainty: '已确认', status: '待清创' },
      ],
      treatments: ['稳定处置后完成后送', '到达后复查伤情', '收容分类 v5（已完成）'],
      missingInformation: ['胸部 X 线或 B 超', '血气与血常规', '小腿污染程度'],
    },
    classification: {
      label: '收容分类 · v5',
      severity: '重伤风险 · 趋稳',
      treatmentPriority: '紧急救治',
      transportPriority: '后送已完成',
    },
    timing: { window: '早期救治宜在伤后 3 小时内实施', status: '处于建议时限内' },
    gate: {
      status: 'COMPLETED',
      title: '用户确认后完成阶段转换',
      description: '生命状态趋稳并具备转运条件，确认后写入Ⅱ级紧急处置。',
      confirmation: '15:50 已确认后送并转入Ⅱ级；15:52 到达后完成转换。',
    },
    actions: ['复查伤情并执行收容分类', '进入相应医疗组重新确定处置顺序', '结合辅助检查评估是否需要外科复苏'],
    nextStageCapability: '确定性专科手术属Ⅲ级能力，本轮不预设跳级。',
    messages: [
      {
        role: 'user',
        text: '经过稳定处置，呼吸慢下来一些，血压回到104，我们已经把伤员送到旅救护所了。',
      },
      {
        role: 'assistant',
        text: '已结合早期救治任务、紧急处置内容和分级救治机构职责知识块完成到站复评。\n\n**阶段确认**：呼吸26次/分、收缩压104mmHg、心率106次/分，生命状态较前好转并已完成后送，阶段在您上一轮确认的基础上写入Ⅱ级早期救治—紧急处置，当前地点为旅（团）救护所，生成收容分类 v5。\n\n**当前救治方案**：按紧急处置要求复查伤情并完成检伤分类，安排胸部影像、血气与血常规等辅助检查以明确胸部损伤性质；继续抗休克治疗与连续生命体征监测；对右小腿开放伤评估污染程度并准备清创。所有侵入性操作须由具备资质的专业人员按指征实施。\n\n**下一步**：待辅助检查结果回报后，再判断是否需要外科复苏或进一步向Ⅲ级专科治疗转换，本轮不预设跳级。\n\n仅供辅助，须具备资质的医务人员复核。',
      },
    ],
    evidence: [
      {
        id: 'r5-e1',
        title: '第二十五条【早期救治—紧急处置】',
        score: '相关度 0.98',
        text: '紧急处置包括检伤分类、辅助检查、紧急处置、抗休克和生命体征监测。',
        ...sharedEvidence,
      },
      {
        id: 'r5-e2',
        title: '第十七条【收容分类】',
        score: '相关度 0.96',
        text: '收容分类应复查伤情并将伤员送往相应组室处置。',
        ...sharedEvidence,
      },
    ],
  },
];
